# Generated by Django 5.1.4 on 2025-01-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0002_genero_tablatemporalgenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
