# Generated by Django 5.1.4 on 2025-01-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0004_alter_cancion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
