# Generated by Django 5.1.4 on 2025-01-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0005_alter_genero_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
