# Generated by Django 5.1.4 on 2025-01-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0006_remove_genero_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='genero',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
