# Generated by Django 5.1.4 on 2025-01-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0007_genero_descripcion_genero_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
