# Generated by Django 5.1.4 on 2025-01-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0008_alter_cancion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
