# Generated by Django 5.1.4 on 2025-01-22 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0009_alter_genero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdSpotify.genero'),
        ),
    ]
