# Generated by Django 5.1.4 on 2025-01-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0011_delete_tablatemporalgenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='canciones',
            field=models.ManyToManyField(blank=True, related_name='listas', to='bdSpotify.cancion'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidadCanciones', models.IntegerField(blank=True, null=True)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('oyentes', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='bdSpotify.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cancion',
            name='albumTemporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='bdSpotify.album'),
        ),
    ]
