# Generated by Django 5.1.4 on 2025-01-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0012_alter_lista_canciones_album_cancion_albumtemporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='album',
        ),
    ]
