# Generated by Django 5.1.4 on 2025-01-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0013_remove_cancion_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='albumTemporal',
            new_name='album',
        ),
    ]
